name: run-tests-on-push
run-name: ${{ github.actor }} is running tests
on: [push]
jobs:
  run-it:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.6.9'
      - name: Install Cython
        run: sudo apt-get install -y cython3
      - name: Running tests
        run: make tests
      - name: Install extra dependencies
        run: sudo apt-get install -y gnuplot
      - name: Running slow tests and examples
        run: make tests-all

